### ISSUE TITLE
Would you accept a PR of changes added in my fork?

### ISSUE THREAD

**Issue by iambumblehead** [ohanhi/hyperscript-helpers#29]
Would you accept a PR of [changes added in my fork](https://github.com/iambumblehead/hyperscript-helpers-opts)? I made a [small demo of the new functions here](https://github.com/iambumblehead/hyperscript-helpers-opts/blob/master/demo/start.js).

These changes make it easier for me to reuse page object code for multiple locations.

**Comment by ohanhi** [comment]
Hi, thanks for asking! I am trying to keep this library as simple as possible, so that others (like yourself) can easily base their work on this. In that sense, I think it is best not to include your efforts into the "main" hyperscript-helpers.

You are welcome to publish your variant as a separate package on npm, of course, like [react-hyperscript-helpers](https://www.npmjs.com/package/react-hyperscript-helpers) was.

**Comment by iambumblehead** [comment]
@ohanhi thanks for the response :)

**Comment by ohanhi** [comment]
:)
